### ISSUE TITLE
GPN18 talk feedback

### ISSUE THREAD

**Issue by neuhalje** [neuhalje/presentation_content-encryption#1]
I welcome all feedback on [my talk at the GPN18](https://pretalx.entropia.de/gpn18/talk/CEQKHF/). 

Nobody wants to listen to a boring talk! And nobody wants to give a boring talk! 

**Please help to improve by  adding feedback as comment!**

___ TEMPLATE ___

## Overall

* _Overall rating (0 to 5)_: 
* _Watched (live/recording)_: 
* _Comment_:

### Presentation

* _I understood you (pronunciation, ..)_:
* _I liked your slides (not, a lot, ..)_: 

### Topic

* _The talk delivered its promise_:
* _I learned something new (yes, no, a lot, ..)_:
* _Would recommend to a friend_:

### More of ... less of

* _Please do more of ..._:
* _Please keep this_:
* _Please do less of_:

**Comment by pRiVi** [comment]
## Overall
- Overall rating (0 to 5): 3
- Watched (live/recording): recording
- Comment: Question: On the ACL scenario, where each record is crypted, how should a system present the user the data? Isn't it the case that such system cannot make any sense beside sending the user the data, without any functionality like filtering, searching, and so on?
## Presentation
- I understood you (pronunciation, ..): Good
- I liked your slides (not, a lot, ..): Yes, good work.
## Topic
- The talk delivered its promise: Too much theoretically stuff... "Practical" means things working in real-world.
- I learned something new (yes, no, a lot, ..): yes... new ideas.
- Would recommend to a friend: Yes
## More of ... less of
- Please do more of ...: Real-world practical solutions
- Please keep this: Declaring how things work
- Please do less of: Less solutions practially makes no sense. Making persons fear by using terms and stories what can go wrong.

**Comment by neuhalje** [comment]
Markus, thank you for your feedback!

For your question: When the data is encrypted the server (normally) must not be able reveal any information, this includes filtering the data on a protected attribute. There are possibilities to do just that, but they all have drawbacks. I have absolutely zero experience with them, so this is _terror incognita_.

Here are some pointers (though I cannot really judge them for accuracy):

* [Secure searchable encryption: a survey](https://link.springer.com/content/pdf/10.1007%2FBF03391580.pdf)
* [Clusion](http://esl.cs.brown.edu/blog/clusion/) is a library for doing encrypted search
* [Papers about searchable encryption (google)](https://scholar.google.de/scholar?q=searchable+symmetric+encryption)
